w3c/wai-intro-wcag

- glance.md
NOTE: Links still need to be updated.
> [Glance] 2.1 Update

- translations.md
added intent for pt-PT Authorized Translation of WCAG 2.1
> added pt-PT

- index.es.md
- new-in-21.es.md
Replaced "Índice de contenidos" with "Contenidos de la página" as agreed in the glossary.
> Page contents heading amend

- content/new-in-21.es.md
- content/new-in-21.md
- content/new-in-22.md
> Remove inline padding-bottom styles without values

- content/index.fr.md
Shawn has asked Sylvie if she wants to update the translation, or wants someone else to...
> [fr] added new content in English

- content/new-in-22.md
Also fix link to understanding which created confusion as reported in w3c/wcag#1835
> Fix Dragging -> Dragging Movements

- content/translations.md
updated intention of translating WCAG 2.1 into French
> updated translation intention

- content/translations.md
The Norwegian authorized translation of WCAG 2.1 is now published! \o/
> Authorized Norwegian Translation completed

- content/translations.md
add: German CAT, unofficial Bulgarian translation
> translations for WCAG 2.1

- content/index.md
> changing bold to test production branch process

- content/faq.md
- content/index.md
- content/new-in-22.md
https://github.com/w3c/wai-intro-wcag/commit/a7e30bb1e708ccfdf2687dd4f1997bbe4ed02a00
https://github.com/w3c/wai-intro-wcag/commit/f7c6a249d02fd0c4ddb48854099d0b4c84a92426
https://github.com/w3c/wai-intro-wcag/commit/9b2ab47cee09e04aaa4f74dbe27440ab32ea4006
> September -> December 2022

- content/translations.md
added: review period for WCAG 2.1 into Catalan started 26 Oct 2022
> WCAG 2.1 into Catalan

- content/new-in-22.md
[preview of In Briefs](https://deploy-preview-196--wai-intro-wcag.netlify.app/standards-guidelines/wcag/new-in-22/#guideline-24-navigable)
> WCAG 2.2 In brief - what - why

- content/non-web-ict.md
@maryjom @daniel-montalvo Here is start of update. Additions and edits welcome! For example, we probably want to put the status of the update more prominently and add a link to the Editor's Draft...
We want to balance between making the status of the draft clear *and* not having to update this page all this time. :-)
> WCAG2ICT Overview update for FPWD August 2023

- content/commenting.md
- content/conformance-logos.md
- content/faq.md
- content/glance.es.md
- content/glance.fr.md
- content/glance.md
- content/glance20.md
- content/index.es.md
- content/index.fr.md
- content/index.md
- content/new-in-21.es.md
- content/new-in-21.md
- content/new-in-22.md
- content/non-web-ict.md
- content/translations.md
- content/wcag3-intro.md
For a cleaner history, I suggest to ["Squash and merge"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits) this pull request. See [how-to ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request)here.
> Delete deprecated links to Wiki page

- content/index.es.md
- content/index.fr.md
- content/index.md
- content/new-in-22.md
- Add comments for translators in frontmatter
- Reorder frontmatter parameters
- Add `last_updated` value in "New in WCAG 2.2"
- Use relative links when linked-to page is in WAI website.
- Fix link to i18n FAQ section in "New in WCAG 2.2"
> Make "WCAG 2 Overview" & "New in WCAG 2.2" ready for translations

- .gitmodules
- _data/standards-translations.yml
- _data/standards.yml
- content/translations.md
Dependencies:
- Merge https://github.com/w3c/wai-website-data/pull/122 with this PR
- Merge https://github.com/w3c/wai-website/pull/395 with this PR
> New WCAG Translations listing

- content/translations.md
I forgot the date in the footer is not based on the `last_updated` date in the frontmatter...
> Update last updated date in footer

- content/index.md
To make it ready for translations:
- Use relative links when possible
- Always use HTTPS
- Link to WCAG 2.2 documents
- Fix link to i18n question in FAQ
- Recently updated: French
- Outdated version: Spanish
- In-progress new translations: Czech, Indonesian
- New translation intent: Polish
> Update WCAG 2 Overview

- content/index.es.md
Spanish content updated. Previewing before requesting a review.
Resolves https://github.com/w3c/wai-translations/issues/243
> [READY FOR REVIEW] Spanish translation update

- content/new-in-22.md
> minor punctuation fixes
